### ISSUE TITLE
Sidebar overlap instead of squish?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/bamboo#2]
The sidebar "squishes" the main content when opened on a small width screen. Would it be more pleasant as an overlapping pane instead of squishing in right beside it?

![Screen Shot 2019-11-08 at 8 50 03 AM](https://user-images.githubusercontent.com/871421/68485657-4db4ad80-0205-11ea-969a-de1043612a4e.jpg)

**Comment by ghost** [comment]
The idea is to use the site with the sidebar shown (as per the large screen functionality), so making it overlay (and then having to hide it to see the content) would cause an inconsistency between screen sizes...

On small screens you have to close the sidebar to see the content regardless, so I'm inclined to leave this as-is for the sake of consistency.

**Comment by ghost** [comment]
Actually, I'll leave this open as I may end up being convinced by it... Be interesting to hear what others think too.

**Comment by ghost** [comment]
So it seems this should be easy enough for anyone to do themselves if they want it instead of the current functionality. Just add the following CSS to your theme:

```css
.layout--bamboo .l-sidebar {
  background: #fff;
  z-index: 99;
}
@media (max-width: 899px) {
  .layout--bamboo.sidebar-active .l-main {
    width: 100%;
  }
}
```
